import ActivityPanel from "./Activity/ActivityPanel";
import Activity from "./Activity/Activity";
import Complaintsview from "./Complaint/Complainsview";
import Dash from "./Dashboard/Dash";
import EventFormCreation from "./Event/EventFormCreate";
import FullEvents from "./Event/EventFullView";
import EventModifier from "./Event/EventModify";
import Eventviewresp from "./Event/EventResponse";
import History from "./History/History";
import ForgAdmPass from "./Login/ForgAdmPass";
import Login from "./Login/Login";
import Forward from "./Complaint/MoreInfo";
import PersonalInfo from "./Account/PersonalInfo";
import Events from "./Event/Events";
import FacultyInfo from "./Complaint/FacultyInfo";
import Admincalendar from "./Dashboard/Admincalendar";
export {Activity,ActivityPanel,Complaintsview,Dash,EventFormCreation,ForgAdmPass,History,EventModifier,Eventviewresp,FullEvents,Login,Forward,PersonalInfo,Events,FacultyInfo,Admincalendar};